/**
 * Directory Tests
 * Generated by Arc CLI
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createAppInstance } from '../src/app.js';
import type { FastifyInstance } from 'fastify';

describe('Directory Resource', () => {
  let app: FastifyInstance;

  beforeAll(async () => {
    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/test-directory';
    await mongoose.connect(testDbUri);
    app = await createAppInstance();
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await mongoose.connection.close();
  });

  describe('GET /directorys', () => {
    it('should return a list', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/directorys',
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('docs');
    });
  });
});
