/**
 * Example Resource Tests
 * Generated by Arc CLI
 *
 * Run tests: npm test
 * Watch mode: npm run test:watch
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createAppInstance } from '../src/app.js';
import type { FastifyInstance } from 'fastify';

describe('Example Resource', () => {
  let app: FastifyInstance;

  beforeAll(async () => {
    // Connect to test database
    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/fajr-be-arc-test';
    await mongoose.connect(testDbUri);

    // Create app instance
    app = await createAppInstance();
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await mongoose.connection.close();
  });

  describe('GET /examples', () => {
    it('should return a list of examples', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/examples',
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('docs');
      expect(Array.isArray(body.docs)).toBe(true);
    });
  });

  describe('POST /examples', () => {
    it('should require authentication', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/examples',
        payload: { name: 'Test Example' },
      });

      // Should fail without auth token
      expect(response.statusCode).toBe(401);
    });
  });

  // Add more tests as needed:
  // - GET /examples/:id
  // - PATCH /examples/:id
  // - DELETE /examples/:id
  // - Custom endpoints
});
