/**
 * Directory Controller
 * Generated by Arc CLI
 */

import { BaseController } from '@classytic/arc';
import directoryRepository from './directory.repository.js';
import { directorySchemaOptions } from './directory.schemas.js';

class DirectoryController extends BaseController {
  constructor() {
    super(directoryRepository as any, { schemaOptions: directorySchemaOptions });
  }

  // Add custom controller methods here
}

const directoryController = new DirectoryController();
export default directoryController;
