/**
 * Directory Schemas
 * Generated by Arc CLI
 */

import Directory from './directory.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 */
const crudSchemas = buildCrudSchemasFromModel(Directory, {
  strictAdditionalProperties: true,
  fieldRules: {
    // Mark fields as system-managed (excluded from create/update)
    // deletedAt: { systemManaged: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
});

// Schema options for controller
export const directorySchemaOptions: any = {
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
};

export default crudSchemas;
