/**
 * Directory Repository
 * Generated by Arc CLI
 */

import { Repository } from "@classytic/mongokit";
import type { DirectoryDocument } from "./directory.model.js";
import Directory from "./directory.model.js";

class DirectoryRepository extends Repository<DirectoryDocument> {
  constructor() {
    super(Directory as any, []);
  }

  /**
   * Find all active records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }

  /**
   * Get directory by slug
   */
  async getBySlug(
    slug: string,
    options?: { select?: string; populate?: string },
  ) {
    return this.getByQuery({ slug }, options);
  }
}

const directoryRepository = new DirectoryRepository();
export default directoryRepository;
export { DirectoryRepository };
