/**
 * Directory Resource
 * Generated by Arc CLI
 */

import { defineResource } from "@classytic/arc";
import { createAdapter } from "#shared/adapter.js";
import { publicReadPermissions } from "#shared/permissions.js";
import Directory from "./directory.model.js";
import directoryRepository from "./directory.repository.js";
import directoryController from "./directory.controller.js";
// import { multiTenantPreset } from "@classytic/arc/presets";

const directoryResource = defineResource({
  name: "directory",
  displayName: "Directories",
  prefix: "/directories",

  adapter: createAdapter(Directory, directoryRepository),
  controller: directoryController,

  presets: [
    "slugLookup",
    // multiTenantPreset({ allowPublic: ["list", "get"] })
  ],

  permissions: publicReadPermissions,

  // Add custom routes here:
  // additionalRoutes: [
  //   {
  //     method: 'GET',
  //     path: '/custom',
  //     summary: 'Custom endpoint',
  //     handler: async (request, reply) => { ... },
  //   },
  // ],
});

export default directoryResource;
