/**
 * Example Resource
 * Generated by Arc CLI
 *
 * A complete resource with:
 * - Model (Mongoose schema)
 * - Repository (MongoKit with plugins)
 * - Permissions (role-based access)
 * - Presets (soft delete, multi-tenant)
 */

import { defineResource } from '@classytic/arc';
import { createAdapter } from '#shared/adapter.js';
import { publicReadPermissions } from '#shared/permissions.js';
import { flexibleMultiTenantPreset } from '#shared/presets/flexible-multi-tenant.js';
import Example from './example.model.js';
import exampleRepository from './example.repository.js';
import exampleController from './example.controller.js';

const exampleResource = defineResource({
  name: 'example',
  displayName: 'Examples',
  prefix: '/examples',

  adapter: createAdapter(Example, exampleRepository),
  controller: exampleController,

  presets: [
    'softDelete',
    flexibleMultiTenantPreset({ tenantField: 'organizationId' }),
  ],

  permissions: publicReadPermissions,

  // Add custom routes here:
  // additionalRoutes: [
  //   {
  //     method: 'GET',
  //     path: '/custom',
  //     summary: 'Custom endpoint',
  //     handler: async (request, reply) => { ... },
  //   },
  // ],
});

export default exampleResource;
