/**
 * Example Model
 * Generated by Arc CLI
 */

import mongoose from 'mongoose';

const exampleSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true, index: true },
    organizationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true, index: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    deletedAt: { type: Date, default: null, index: true },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes for common queries
exampleSchema.index({ name: 1 });
exampleSchema.index({ deletedAt: 1, isActive: 1 });
exampleSchema.index({ organizationId: 1, deletedAt: 1 });

export type ExampleDocument = mongoose.InferSchemaType<typeof exampleSchema>;
export type ExampleModel = mongoose.Model<ExampleDocument>;

const Example = mongoose.model<ExampleDocument>('Example', exampleSchema);

export default Example;
