/**
 * Example Repository
 * Generated by Arc CLI
 *
 * MongoKit repository with plugins for:
 * - Soft delete (deletedAt filtering)
 * - Custom business logic methods
 */

import {
  Repository,
  softDeletePlugin,
  methodRegistryPlugin,
} from '@classytic/mongokit';
import type { ExampleDocument } from './example.model.js';
import Example from './example.model.js';

class ExampleRepository extends Repository<ExampleDocument> {
  constructor() {
    super(Example, [
      methodRegistryPlugin(),  // Required for plugin method registration
      softDeletePlugin(),      // Soft delete support
    ]);
  }

  /**
   * Find all active (non-deleted) records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }

  /**
   * Find active records for an organization
   */
  async findActiveByOrg(organizationId: string) {
    return this.Model.find({
      organizationId,
      isActive: true,
      deletedAt: null,
    }).lean();
  }

  // Note: softDeletePlugin provides restore() and getDeleted() methods automatically
}

const exampleRepository = new ExampleRepository();

export default exampleRepository;
export { ExampleRepository };
