/**
 * Example Schemas
 * Generated by Arc CLI
 *
 * Schema options for controller validation and query parsing
 */

import Example from './example.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 * Auto-generated from Mongoose model
 */
const crudSchemas = buildCrudSchemasFromModel(Example, {
  strictAdditionalProperties: true,
  fieldRules: {
    // Mark fields as system-managed (excluded from create/update)
    // deletedAt: { systemManaged: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',
      organizationId: 'ObjectId',
      createdAt: 'date',
    },
  },
});

// Schema options for controller
export const exampleSchemaOptions: any = {
  query: {
    allowedPopulate: ['organizationId'],
    filterableFields: {
      isActive: 'boolean',
      organizationId: 'ObjectId',
      createdAt: 'date',
    },
  },
};

export default crudSchemas;
