/**
 * Example Controller
 * Generated by Arc CLI
 *
 * BaseController provides CRUD operations with:
 * - Automatic pagination
 * - Query parsing
 * - Validation
 */

import { BaseController } from '@classytic/arc';
import exampleRepository from './example.repository.js';
import { exampleSchemaOptions } from './example.schemas.js';

class ExampleController extends BaseController {
  constructor() {
    super(exampleRepository as any, { schemaOptions: exampleSchemaOptions });
  }

  // Add custom controller methods here:
  // async customAction(request, reply) {
  //   // Custom logic
  // }
}

const exampleController = new ExampleController();
export default exampleController;
