/**
 * Auth Resource
 * Generated by Arc CLI
 *
 * Combined auth + user profile endpoints:
 * - POST /auth/register
 * - POST /auth/login
 * - POST /auth/refresh
 * - POST /auth/forgot-password
 * - POST /auth/reset-password
 * - GET /users/me
 * - PATCH /users/me
 */

import { defineResource } from '@classytic/arc';
import { allowPublic, requireAuth } from '@classytic/arc/permissions';
import { createAdapter } from '#shared/adapter.js';
import User from '../user/user.model.js';
import userRepository from '../user/user.repository.js';
import * as handlers from './auth.handlers.js';
import * as schemas from './auth.schemas.js';

/**
 * Auth Resource - handles authentication
 */
export const authResource = defineResource({
  name: 'auth',
  displayName: 'Authentication',
  tag: 'Authentication',
  prefix: '/auth',

  adapter: createAdapter(User as any, userRepository as any),
  disableDefaultRoutes: true,

  additionalRoutes: [
    {
      method: 'POST',
      path: '/register',
      summary: 'Register new user',
      permissions: allowPublic(),
      handler: handlers.register,
      wrapHandler: false,
      schema: { body: schemas.registerBody },
    },
    {
      method: 'POST',
      path: '/login',
      summary: 'User login',
      permissions: allowPublic(),
      handler: handlers.login,
      wrapHandler: false,
      schema: { body: schemas.loginBody },
    },
    {
      method: 'POST',
      path: '/refresh',
      summary: 'Refresh access token',
      permissions: allowPublic(),
      handler: handlers.refreshToken,
      wrapHandler: false,
      schema: { body: schemas.refreshBody },
    },
    {
      method: 'POST',
      path: '/forgot-password',
      summary: 'Request password reset',
      permissions: allowPublic(),
      handler: handlers.forgotPassword,
      wrapHandler: false,
      schema: { body: schemas.forgotBody },
    },
    {
      method: 'POST',
      path: '/reset-password',
      summary: 'Reset password with token',
      permissions: allowPublic(),
      handler: handlers.resetPassword,
      wrapHandler: false,
      schema: { body: schemas.resetBody },
    },
  ],
});

/**
 * User Profile Resource - handles /users/me
 */
export const userProfileResource = defineResource({
  name: 'user-profile',
  displayName: 'User Profile',
  tag: 'User Profile',
  prefix: '/users',

  adapter: createAdapter(User as any, userRepository as any),
  disableDefaultRoutes: true,

  additionalRoutes: [
    {
      method: 'GET',
      path: '/me',
      summary: 'Get current user profile',
      permissions: requireAuth(),
      handler: handlers.getUserProfile,
      wrapHandler: false,
    },
    {
      method: 'PATCH',
      path: '/me',
      summary: 'Update current user profile',
      permissions: requireAuth(),
      handler: handlers.updateUserProfile,
      wrapHandler: false,
      schema: { body: schemas.updateUserBody },
    },
  ],
});

export default authResource;
