/**
 * Auth Handlers
 * Generated by Arc CLI
 */

import jwt from 'jsonwebtoken';
import config from '#config/index.js';
import userRepository from '../user/user.repository.js';

import type { FastifyRequest, FastifyReply } from 'fastify';

// Token helpers
function generateTokens(userId: string) {
  const accessToken = jwt.sign({ id: userId }, config.jwt.secret, { expiresIn: '15m' });
  const refreshToken = jwt.sign({ id: userId }, config.jwt.refreshSecret, { expiresIn: '7d' });
  return { accessToken, refreshToken };
}

/**
 * Register new user
 */
export async function register(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { name, email, password } = request.body as any;

    // Check if email exists
    if (await userRepository.emailExists(email)) {
      return reply.code(400).send({ success: false, message: 'Email already registered' });
    }

    // Create user
    await userRepository.create({ name, email, password, roles: ['user'] });

    return reply.code(201).send({ success: true, message: 'User registered successfully' });
  } catch (error) {
    request.log.error({ err: error }, 'Register error');
    return reply.code(500).send({ success: false, message: 'Registration failed' });
  }
}

/**
 * Login user
 */
export async function login(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { email, password } = request.body as any;

    const user = await userRepository.findByEmail(email);
    if (!user || !(await user.matchPassword(password))) {
      return reply.code(401).send({ success: false, message: 'Invalid credentials' });
    }

    const tokens = generateTokens(user._id.toString());

    return reply.send({
      success: true,
      user: { id: user._id, name: user.name, email: user.email, roles: user.roles },
      ...tokens,
    });
  } catch (error) {
    request.log.error({ err: error }, 'Login error');
    return reply.code(500).send({ success: false, message: 'Login failed' });
  }
}

/**
 * Refresh access token
 */
export async function refreshToken(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { token } = request.body as any;
    if (!token) {
      return reply.code(401).send({ success: false, message: 'Refresh token required' });
    }

    const decoded = jwt.verify(token, config.jwt.refreshSecret) as { id: string };
    const tokens = generateTokens(decoded.id);

    return reply.send({ success: true, ...tokens });
  } catch {
    return reply.code(401).send({ success: false, message: 'Invalid refresh token' });
  }
}

/**
 * Forgot password
 */
export async function forgotPassword(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { email } = request.body as any;
    const user = await userRepository.findByEmail(email);

    if (user) {
      const token = Math.random().toString(36).slice(2) + Date.now().toString(36);
      const expires = new Date(Date.now() + 3600000); // 1 hour
      await userRepository.setResetToken(user._id, token, expires);
      // TODO: Send email with reset link
      request.log.info(`Password reset token for ${email}: ${token}`);
    }

    // Always return success to prevent email enumeration
    return reply.send({ success: true, message: 'If email exists, reset link sent' });
  } catch (error) {
    request.log.error({ err: error }, 'Forgot password error');
    return reply.code(500).send({ success: false, message: 'Failed to process request' });
  }
}

/**
 * Reset password
 */
export async function resetPassword(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { token, newPassword } = request.body as any;
    const user = await userRepository.findByResetToken(token);

    if (!user) {
      return reply.code(400).send({ success: false, message: 'Invalid or expired token' });
    }

    await userRepository.updatePassword(user._id, newPassword);
    return reply.send({ success: true, message: 'Password has been reset' });
  } catch (error) {
    request.log.error({ err: error }, 'Reset password error');
    return reply.code(500).send({ success: false, message: 'Failed to reset password' });
  }
}

/**
 * Get current user profile
 */
export async function getUserProfile(request: FastifyRequest, reply: FastifyReply) {
  try {
    const userId = (request as any).user?._id || (request as any).user?.id;
    const user = await userRepository.getById(userId);

    if (!user) {
      return reply.code(404).send({ success: false, message: 'User not found' });
    }

    return reply.send({ success: true, data: user });
  } catch (error) {
    request.log.error({ err: error }, 'Get profile error');
    return reply.code(500).send({ success: false, message: 'Failed to get profile' });
  }
}

/**
 * Update current user profile
 */
export async function updateUserProfile(request: FastifyRequest, reply: FastifyReply) {
  try {
    const userId = (request as any).user?._id || (request as any).user?.id;
    const updates = { ...request.body as any };

    // Prevent updating protected fields
    if ('password' in updates) delete updates.password;
    if ('roles' in updates) delete updates.roles;
    if ('organizations' in updates) delete updates.organizations;

    const user = await userRepository.Model.findByIdAndUpdate(userId, updates, { new: true });
    return reply.send({ success: true, data: user });
  } catch (error) {
    request.log.error({ err: error }, 'Update profile error');
    return reply.code(500).send({ success: false, message: 'Failed to update profile' });
  }
}
