/**
 * Financial Report Routes
 *
 * All reports are generated by the @classytic/ledger engine
 * using MongoDB aggregation pipelines. No hand-written queries.
 *
 * Endpoints:
 *   GET /reports/trial-balance
 *   GET /reports/balance-sheet
 *   GET /reports/income-statement
 *   GET /reports/general-ledger
 *   GET /reports/cash-flow
 */

import type { FastifyPluginAsync } from 'fastify';
import mongoose from 'mongoose';
import accounting from '#config/accounting.js';
import { Account } from '../account/account.model.js';
import { JournalEntry } from '../journal-entry/journal-entry.model.js';

/**
 * Convert string organizationId to ObjectId for aggregate pipelines.
 * Mongoose .find() auto-casts, but .aggregate() does NOT — so reports
 * (which use aggregation) need explicit ObjectId conversion.
 */
function toObjectId(id: string): mongoose.Types.ObjectId {
  return new mongoose.Types.ObjectId(id);
}

/**
 * Parse date option from query parameters.
 * Supports: month, quarter, year, custom range.
 */
export function parseDateParams(query: any) {
  const { dateOption = 'year', year, month, quarter, startDate, endDate, date } =
    query;

  if (dateOption === 'custom' && startDate && endDate) {
    return {
      dateOption: 'custom' as const,
      dateValue: {
        start: new Date(startDate as string),
        end: new Date(endDate as string),
      },
    };
  }

  if (dateOption === 'month' && (date || month || year)) {
    // Frontend sends `date` param (e.g. "2026-10-01"), backend also accepts `month`
    const raw = date || month;
    const d = raw ? new Date(raw as string) : new Date(`${year}-01-01`);
    return { dateOption: 'month' as const, dateValue: d };
  }

  if (dateOption === 'quarter' && quarter && year) {
    return {
      dateOption: 'quarter' as const,
      dateValue: { quarter: parseInt(quarter as string, 10), year: parseInt(year as string, 10) },
    };
  }

  // Default: current year
  return {
    dateOption: 'year' as const,
    dateValue: parseInt((year as string) || String(new Date().getFullYear()), 10),
  };
}

const reportRoutes: FastifyPluginAsync = async (fastify) => {
  // Require authentication + org context for all report routes
  const authenticate = (fastify as any).authenticate;
  if (authenticate) {
    fastify.addHook('preHandler', authenticate);
  }

  const reports = accounting.createReports({ Account, JournalEntry });

  // GET /reports/trial-balance
  fastify.get('/trial-balance', async (req: any, reply) => {
    const orgId = req.scope?.organizationId;
    if (!orgId) {
      return reply.status(400).send({ error: 'Organization context required' });
    }
    const { dateOption, dateValue } = parseDateParams(req.query);
    const result = await reports.trialBalance({
      organizationId: toObjectId(orgId),
      dateOption,
      dateValue,
      accountId: (req.query as any).accountId,
    });
    return { success: true, data: result };
  });

  // GET /reports/balance-sheet
  fastify.get('/balance-sheet', async (req: any, reply) => {
    const orgId = req.scope?.organizationId;
    if (!orgId) {
      return reply.status(400).send({ error: 'Organization context required' });
    }
    const { dateOption, dateValue } = parseDateParams(req.query);
    const result = await reports.balanceSheet({
      organizationId: toObjectId(orgId),
      dateOption,
      dateValue,
      businessName: (req.query as any).businessName,
    });
    return { success: true, data: result };
  });

  // GET /reports/income-statement (also aliased as /reports/income for frontend compat)
  const incomeStatementHandler = async (req: any, reply: any) => {
    const orgId = req.scope?.organizationId;
    if (!orgId) {
      return reply.status(400).send({ error: 'Organization context required' });
    }
    const { dateOption, dateValue } = parseDateParams(req.query);
    const result = await reports.incomeStatement({
      organizationId: toObjectId(orgId),
      dateOption,
      dateValue,
    });
    return { success: true, data: result };
  };
  fastify.get('/income-statement', incomeStatementHandler);
  fastify.get('/income', incomeStatementHandler);

  // GET /reports/general-ledger
  fastify.get('/general-ledger', async (req: any, reply) => {
    const orgId = req.scope?.organizationId;
    if (!orgId) {
      return reply.status(400).send({ error: 'Organization context required' });
    }
    const { dateOption, dateValue } = parseDateParams(req.query);
    const result = await reports.generalLedger({
      organizationId: toObjectId(orgId),
      dateOption,
      dateValue,
      accountId: (req.query as any).accountId,
    });

    // Filter out zero-balance accounts with no entries, and slim down account objects
    const accounts = result.accounts
      .filter((a: any) => a.openingBalance !== 0 || a.closingBalance !== 0 || a.entries.length > 0)
      .map((a: any) => ({
        account: {
          _id: a.account._id,
          accountTypeCode: a.account.accountTypeCode,
          accountNumber: a.account.accountNumber,
          name: a.account.name,
          isCashAccount: a.account.isCashAccount,
        },
        openingBalance: a.openingBalance,
        entries: a.entries,
        closingBalance: a.closingBalance,
      }));

    return { success: true, data: { accounts, period: result.period } };
  });

  // GET /reports/cash-flow
  fastify.get('/cash-flow', async (req: any, reply) => {
    const orgId = req.scope?.organizationId;
    if (!orgId) {
      return reply.status(400).send({ error: 'Organization context required' });
    }
    const { dateOption, dateValue } = parseDateParams(req.query);
    const result = await reports.cashFlow({
      organizationId: toObjectId(orgId),
      dateOption,
      dateValue,
      businessName: (req.query as any).businessName,
    });
    return { success: true, data: result };
  });
};

export default reportRoutes;
