/**
 * User Repository
 * Generated by Arc CLI
 *
 * MongoKit repository with plugins for common operations
 */

import {
  Repository,
  methodRegistryPlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
import type { UserDocument } from './model.js';
import type { ClientSession, Types } from 'mongoose';
import User from './user.model.js';

type ID = string | Types.ObjectId;

class UserRepository extends Repository<UserDocument> {
  constructor() {
    super(User as any, [
      methodRegistryPlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find user by email
   */
  async findByEmail(email: string) {
    return this.Model.findOne({ email: email.toLowerCase().trim() });
  }

  /**
   * Find user by reset token
   */
  async findByResetToken(token: string) {
    return this.Model.findOne({
      resetPasswordToken: token,
      resetPasswordExpires: { $gt: Date.now() },
    });
  }

  /**
   * Check if email exists
   */
  async emailExists(email: string): Promise<boolean> {
    const result = await this.Model.exists({ email: email.toLowerCase().trim() });
    return !!result;
  }

  /**
   * Update user password (triggers hash middleware)
   */
  async updatePassword(userId: ID, newPassword: string, options: { session?: ClientSession } = {}) {
    const user = await this.Model.findById(userId).session(options.session ?? null);
    if (!user) throw new Error('User not found');

    user.password = newPassword;
    user.resetPasswordToken = undefined;
    user.resetPasswordExpires = undefined;
    await user.save({ session: options.session ?? undefined });
    return user;
  }

  /**
   * Set reset token
   */
  async setResetToken(userId: ID, token: string, expiresAt: Date) {
    return this.Model.findByIdAndUpdate(
      userId,
      { resetPasswordToken: token, resetPasswordExpires: expiresAt },
      { new: true }
    );
  }

  /**
   * Find users by organization
   */
  async findByOrganization(organizationId: ID) {
    return this.Model.find({ 'organizations.organizationId': organizationId })
      .select('-password -resetPasswordToken -resetPasswordExpires')
      .lean();
  }

}

const userRepository = new UserRepository();
export default userRepository;
export { UserRepository };
