/**
 * User Controller
 * Generated by Arc CLI
 *
 * BaseController for user management operations.
 * Used by auth resource for /users/me endpoints.
 */

import { BaseController } from '@classytic/arc';
import userRepository from './user.repository.js';

class UserController extends BaseController {
  constructor() {
    super(userRepository as any);
  }

  // Custom user operations can be added here
}

const userController = new UserController();
export default userController;
