/**
 * User Model
 * Generated by Arc CLI
 */

import bcrypt from 'bcryptjs';
import mongoose, { type HydratedDocument, type Model, type Types } from 'mongoose';

// Organization roles (for multi-tenant)
const ORG_ROLES = ['owner', 'manager', 'hr', 'staff', 'contractor'] as const;
type OrgRole = typeof ORG_ROLES[number];

const { Schema } = mongoose;

type UserOrganization = {
  organizationId: Types.ObjectId;
  organizationName: string;
  roles: OrgRole[];
  joinedAt: Date;
};

type PlatformRole = 'user' | 'admin' | 'superadmin';

type User = {
  name: string;
  email: string;
  password: string;
  roles: PlatformRole[];
  organizations: UserOrganization[];
  resetPasswordToken?: string;
  resetPasswordExpires?: Date;
};

type UserMethods = {
  matchPassword: (enteredPassword: string) => Promise<boolean>;
  getOrgRoles: (orgId: Types.ObjectId | string) => OrgRole[];
  hasOrgAccess: (orgId: Types.ObjectId | string) => boolean;
  addOrganization: (orgId: Types.ObjectId, name: string, roles?: OrgRole[]) => UserDocument;
  removeOrganization: (orgId: Types.ObjectId) => UserDocument;
};

export type UserDocument = HydratedDocument<User, UserMethods>;
export type UserModel = Model<User, {}, UserMethods>;

const userSchema = new Schema<User, UserModel, UserMethods>(
  {
    name: { type: String, required: true, trim: true },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    password: { type: String, required: true },

    // Platform roles
    roles: {
      type: [String],
      enum: ['user', 'admin', 'superadmin'],
      default: ['user'],
    },

    // Multi-org support
    organizations: [{
      organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', required: true },
      organizationName: { type: String, required: true },
      roles: { type: [String], enum: ORG_ROLES, default: [] },
      joinedAt: { type: Date, default: () => new Date() },
    }],

    // Password reset
    resetPasswordToken: String,
    resetPasswordExpires: Date,
  },
  { timestamps: true }
);

// Password hashing
userSchema.pre('save', async function() {
  if (!this.isModified('password')) return;
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

// Password comparison
userSchema.methods.matchPassword = async function(enteredPassword: string) {
  return bcrypt.compare(enteredPassword, this.password);
};

// Organization methods
userSchema.methods.getOrgRoles = function(orgId: Types.ObjectId | string) {
  const org = this.organizations.find(o => o.organizationId.toString() === orgId.toString());
  return org?.roles || [];
};

userSchema.methods.hasOrgAccess = function(orgId: Types.ObjectId | string) {
  return this.organizations.some(o => o.organizationId.toString() === orgId.toString());
};

userSchema.methods.addOrganization = function(
  organizationId: Types.ObjectId,
  organizationName: string,
  roles: OrgRole[] = []
) {
  const existing = this.organizations.find(o => o.organizationId.toString() === organizationId.toString());
  if (existing) {
    existing.organizationName = organizationName;
    existing.roles = [...new Set([...existing.roles, ...roles])];
  } else {
    this.organizations.push({ organizationId, organizationName, roles, joinedAt: new Date() });
  }
  return this;
};

userSchema.methods.removeOrganization = function(organizationId: Types.ObjectId) {
  this.organizations = this.organizations.filter(o => o.organizationId.toString() !== organizationId.toString());
  return this;
};

// Index for org queries
userSchema.index({ 'organizations.organizationId': 1 });

// Exclude password in JSON
userSchema.set('toJSON', {
  transform: (_doc, ret: any) => {
    delete ret.password;
    delete ret.resetPasswordToken;
    delete ret.resetPasswordExpires;
    return ret;
  },
});

const User = mongoose.models.User as UserModel || mongoose.model<User, UserModel>('User', userSchema);
export default User;
