/**
 * fajr-be-arc - App Factory
 * Generated by Arc CLI
 *
 * Creates and configures the Fastify app instance.
 * Can be imported by:
 * - index.ts (HTTP server)
 * - worker.ts (background workers)
 * - tests (integration tests)
 */

import type { FastifyInstance } from 'fastify';
import config from '#config/index.js';
import { createApp } from '@classytic/arc/factory';

// App-specific plugins
import { registerPlugins } from '#plugins/index.js';

// Resource registry
import { registerResources } from '#resources/index.js';

/**
 * Create a fully configured app instance
 *
 * @returns Configured Fastify instance ready to use
 */
export async function createAppInstance(): Promise<FastifyInstance> {
  // Create Arc app with base configuration
  const app = await createApp({
    preset: config.env === 'production' ? 'production' : 'development',
    auth: {
      jwt: { secret: config.jwt.secret },
    },
    cors: {
      origin: config.cors.origins,
    },
  });

  // Register app-specific plugins (explicit dependency injection)
  await registerPlugins(app, { config });

  // Register all resources
  await registerResources(app);

  return app;
}

export default createAppInstance;
