/**
 * fajr-be-arc - Server Entry Point
 * Generated by Arc CLI
 *
 * This file starts the HTTP server.
 * For workers or other entry points, import createAppInstance from './app.js'
 */

// Load environment FIRST (before any other imports)
import '#config/env.js';

import config from '#config/index.js';
import mongoose from 'mongoose';
import { createAppInstance } from './app.js';

async function main(): Promise<void> {
  console.log(`🔧 Environment: ${config.env}`);

  // Connect to MongoDB
  await mongoose.connect(config.database.uri);
  console.log('📦 Connected to MongoDB');

  // Create and configure app
  const app = await createAppInstance();

  // Start server
  await app.listen({ port: config.server.port, host: config.server.host });
  console.log(`🚀 Server running at http://${config.server.host}:${config.server.port}`);
}

main().catch((err) => {
  console.error('❌ Failed to start server:', err);
  process.exit(1);
});
